theme: minima
title: meta.omacneil.og  
author: Dan MacNeil
email: dan@Omacneil.org
description: > # this means to ignore newlines until "baseurl:"
  Non code, non IT related thoughts to disc. Most likely health, fitness, mindfulness, life-hacking, ethics.

# social links
twitter_username: omacneil # DO NOT include the @ character, or else the build will fail!
github_username:  omacneil # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
